(TeX-add-style-hook "ena"
 (lambda ()
    (LaTeX-add-bibliographies
     "srbbib_abb"
     "srb")
    (LaTeX-add-labels
     "tab:alg"
     "fig:fig"
     "sec:data"
     "fig:oyster"
     "tab:structure"
     "tab:flow"
     "tab:asc"
     "tab:storage"
     "tab:utility"
     "tab:mti"
     "fig:aec"
     "tab:TRO"
     "tab:BGC"
     "fig:target"
     "fig:igraph")
    (TeX-add-symbols
     "R"
     "tableline")
    (TeX-run-style-hooks
     "Sweave"
     "sidecap"
     "fontenc"
     "T1"
     "inputenc"
     "utf8x"
     "ucs"
     "hyperref"
     "amsmath"
     "amssymb"
     "natbib"
     "super"
     "sort"
     "geometry"
     "latex2e"
     "art11"
     "article"
     "11pt")))

